'use client';

import { useState, useEffect, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';

export default function ChatHistory() {
  const router = useRouter();
  const [user, setUser] = useState(null);
  const [history, setHistory] = useState([]);
  const [selectedChat, setSelectedChat] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterAudience, setFilterAudience] = useState('all');

  useEffect(() => {
    // Check authentication
    const authToken = localStorage.getItem('authToken');
    const userData = localStorage.getItem('user');

    if (!authToken || !userData) {
      router.push('/login');
      return;
    }

    const parsedUser = JSON.parse(userData);
    // eslint-disable-next-line react-hooks/set-state-in-effect -- Legitimate initialization from localStorage
    setUser((prev) => prev ?? parsedUser);

    // Load history
    const savedHistory = localStorage.getItem('simplificationHistory');
    if (savedHistory) {
      const parsedHistory = JSON.parse(savedHistory);
      setHistory((prev) => prev.length === 0 ? parsedHistory : prev);
    }
  }, [router]);

  // Use useMemo for derived state instead of useEffect + setState
  const filteredHistory = useMemo(() => {
    let filtered = history;

    if (searchTerm) {
      filtered = filtered.filter((chat) =>
        chat.original.toLowerCase().includes(searchTerm.toLowerCase()) ||
        chat.summary.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    if (filterAudience !== 'all') {
      filtered = filtered.filter((chat) => chat.audience === filterAudience);
    }

    return filtered;
  }, [searchTerm, filterAudience, history]);

  const handleDelete = (id) => {
    const updatedHistory = history.filter((chat) => chat.id !== id);
    setHistory(updatedHistory);
    localStorage.setItem('simplificationHistory', JSON.stringify(updatedHistory));
    setSelectedChat(null);
  };

  const handleDownload = (chat) => {
    const content = `Technical Briefing Simplification Report
=====================================

Audience: ${chat.audience}
Date: ${chat.timestamp}

ORIGINAL BRIEFING:
${chat.original}

SIMPLIFIED SUMMARY:
${chat.summary}

---
Generated by Technical Briefing Simplifier
`;
    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `briefing-${chat.id}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (!user) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <Navbar user={user} />

      <main className="max-w-7xl mx-auto px-4 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">Chat History</h1>
          <p className="text-gray-600 dark:text-gray-400">
            View and manage all your previous simplifications
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Sidebar with Filters */}
          <div className="lg:col-span-1">
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-6 sticky top-24">
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Filters</h2>

              {/* Search */}
              <div className="mb-6">
                <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                  Search
                </label>
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Search chats..."
                  className="w-full px-4 py-2 border-2 border-gray-300 dark:border-gray-600 rounded-lg focus:outline-none focus:border-blue-500 dark:bg-gray-700 dark:text-white"
                />
              </div>

              {/* Audience Filter */}
              <div className="mb-6">
                <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                  Audience Level
                </label>
                <select
                  value={filterAudience}
                  onChange={(e) => setFilterAudience(e.target.value)}
                  className="w-full px-4 py-2 border-2 border-gray-300 dark:border-gray-600 rounded-lg focus:outline-none focus:border-blue-500 dark:bg-gray-700 dark:text-white"
                >
                  <option value="all">All Audiences</option>
                  <option value="executive">Executive/C-Level</option>
                  <option value="manager">Manager/Team Lead</option>
                  <option value="client">Client/Stakeholder</option>
                  <option value="general">General Audience</option>
                </select>
              </div>

              {/* Statistics */}
              <div className="bg-gradient-to-br from-blue-50 dark:from-blue-900/20 to-indigo-50 dark:to-indigo-900/20 p-4 rounded-lg">
                <p className="text-sm text-gray-700 dark:text-gray-300 mb-2">
                  <strong>Total Chats:</strong> {history.length}
                </p>
                <p className="text-sm text-gray-700 dark:text-gray-300 mb-2">
                  <strong>Filtered:</strong> {filteredHistory.length}
                </p>
                <p className="text-sm text-gray-700 dark:text-gray-300">
                  <strong>Characters Saved:</strong>{' '}
                  {history.reduce(
                    (total, chat) => total + (chat.original.length - chat.summary.length),
                    0
                  ).toLocaleString()}
                </p>
              </div>
            </div>
          </div>

          {/* Main Content */}
          <div className="lg:col-span-2">
            {filteredHistory.length === 0 ? (
              <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg p-12 text-center">
                <p className="text-4xl mb-4">📭</p>
                <p className="text-xl font-semibold text-gray-900 dark:text-white mb-2">No chats found</p>
                <p className="text-gray-600 dark:text-gray-400">
                  {history.length === 0
                    ? 'Start by creating your first simplification!'
                    : 'Try adjusting your filters.'}
                </p>
              </div>
            ) : (
              <div className="space-y-4">
                {filteredHistory.map((chat) => (
                  <div
                    key={chat.id}
                    onClick={() => setSelectedChat(selectedChat?.id === chat.id ? null : chat)}
                    className={`bg-white dark:bg-gray-800 rounded-xl shadow-md hover:shadow-lg transition cursor-pointer p-6 border-l-4 ${
                      selectedChat?.id === chat.id
                        ? 'border-blue-600 bg-blue-50 dark:bg-blue-900/20'
                        : 'border-gray-300 dark:border-gray-700'
                    }`}
                  >
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <span className="px-3 py-1 bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 text-xs font-semibold rounded-full">
                            {chat.audience}
                          </span>
                          <span className="text-xs text-gray-500 dark:text-gray-400">{chat.timestamp}</span>
                        </div>
                        <p className="text-gray-700 dark:text-gray-300 line-clamp-2 mb-2">
                          {chat.original}
                        </p>
                      </div>
                    </div>

                    {/* Show preview on hover/click */}
                    {selectedChat?.id === chat.id && (
                      <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700 space-y-3">
                        <div>
                          <h4 className="text-sm font-semibold text-gray-900 dark:text-white mb-2">
                            Original Brief ({chat.original.length} chars):
                          </h4>
                          <p className="text-sm text-gray-600 dark:text-gray-400 bg-gray-50 dark:bg-gray-700 p-3 rounded line-clamp-3">
                            {chat.original}
                          </p>
                        </div>

                        <div>
                          <h4 className="text-sm font-semibold text-gray-900 dark:text-white mb-2">
                            Simplified Summary ({chat.summary.length} chars):
                          </h4>
                          <p className="text-sm text-gray-600 dark:text-gray-400 bg-green-50 dark:bg-green-900/20 p-3 rounded line-clamp-4">
                            {chat.summary}
                          </p>
                        </div>

                        <div className="flex gap-2 pt-3">
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDownload(chat);
                            }}
                            className="flex-1 px-4 py-2 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition"
                          >
                            📥 Download
                          </button>
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              navigator.clipboard.writeText(chat.summary);
                              alert('Summary copied to clipboard!');
                            }}
                            className="flex-1 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition"
                          >
                            📋 Copy
                          </button>
                          <button
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDelete(chat.id);
                            }}
                            className="flex-1 px-4 py-2 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition"
                          >
                            🗑️ Delete
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
